import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { parseBrand } from '../src/lib/brand-schema.js';
import { NEVER_AI_FIELDS } from './lib/ai.mjs';
import { checkQuality } from './lib/quality.mjs';

const DATA_DIR = path.join(process.cwd(), 'src', 'data');
const DEFAULT_IN = path.join(process.cwd(), 'brands.generated.json');

function parseArgs(argv) {
  const args = { in: DEFAULT_IN, apply: false, allowMock: false, allowCoreChanges: false, brand: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const next = () => argv[++i];
    if (a === '--apply') args.apply = true;
    else if (a === '--allow-mock') args.allowMock = true;
    else if (a === '--allow-core-changes') args.allowCoreChanges = true;
    else if (a === '--brand') args.brand = next();
    else if (a === '--in') args.in = next();
    else if (a === '--help') args.help = true;
  }
  return args;
}

function readJson(file) {
  try {
    return JSON.parse(readFileSync(file, 'utf-8'));
  } catch (err) {
    throw new Error(`Cannot read ${file}: ${err.message}`);
  }
}

async function main() {
  const args = parseArgs(process.argv.slice(2));

  if (args.help) {
    console.log(`Usage: node scripts/promote-brands.mjs [options]

Options:
  --apply                Write accepted records into src/data/<slug>/brand.json.
                         Without --apply this validates and previews only.
  --allow-mock           Allow promoting records generated by the MOCK provider.
                         DANGEROUS: mock records are synthetic test data.
  --allow-core-changes   Allow overwriting core identity fields (name, slug,
                         description, logo, productionModels, discontinuedModels).
  --brand <slug>         Only consider this brand's record.
  --in <file>            Input generated file. Default: brands.generated.json
  --help                 Show this help.`);
    return;
  }

  const records = readJson(args.in);
  if (!Array.isArray(records)) throw new Error(`${args.in} does not contain an array of records.`);

  console.log(`Loaded ${records.length} record(s) from ${args.in}`);
  console.log(`Mode: ${args.apply ? 'APPLY (writes to src/data)' : 'VALIDATE + PREVIEW only'}`);
  console.log('');

  const wanted = records.filter((r) => (args.brand ? r.slug === args.brand : true));

  let accepted = 0;
  let skipped = 0;
  const rejected = [];

  for (const record of wanted) {
    const slug = record.slug;
    const label = `  ${slug}:`;

    if (record.status !== 'ok') {
      console.log(`  ${slug}: skipped (record status is "${record.status}")`);
      skipped++;
      continue;
    }

    if (record.meta?.source === 'mock-test-data' && !args.allowMock) {
      console.log(`  ${slug}: skipped — MOCK record (synthetic test data). Pass --allow-mock to force (not recommended).`);
      skipped++;
      continue;
    }

    if (!record.brand || typeof record.brand !== 'object') {
      console.log(`  ${slug}: rejected — record has no merged brand object`);
      skipped++;
      continue;
    }

    const schema = parseBrand(record.brand);
    const quality = checkQuality(record.brand, { scope: 'merged' });
    const slugMatches = slugifyCheck(record.brand, slug);

    if (!schema.success || !quality.ok || !slugMatches.ok) {
      const reasons = [
        ...(schema.success ? [] : schema.error.issues.map((i) => `schema:${i.path.join('.')}:${i.message}`)),
        ...quality.errors.map((e) => `quality:${e}`),
        ...(slugMatches.ok ? [] : [slugMatches.message]),
      ];
      rejected.push({ slug, reasons });
      console.log(`  ${slug}: rejected — ${reasons.join('; ')}`);
      skipped++;
      continue;
    }

    let existing = null;
    try {
      existing = readJson(path.join(DATA_DIR, slug, 'brand.json'));
    } catch {
      existing = null;
    }
    if (!existing) {
      console.log(`  ${slug}: skipped — no existing src/data/${slug}/brand.json to merge into`);
      skipped++;
      continue;
    }

    const coreChanged = NEVER_AI_FIELDS.filter((f) => JSON.stringify(existing[f]) !== JSON.stringify(record.brand[f]));
    if (coreChanged.length > 0 && !args.allowCoreChanges) {
      console.log(`  ${slug}: skipped — would change core verified fields (${coreChanged.join(', ')}). Review manually or pass --allow-core-changes.`);
      skipped++;
      continue;
    }

    const changedFields = Object.keys(record.generated || {});
    const apply = args.apply;
    if (apply) {
      writeFileSync(path.join(DATA_DIR, slug, 'brand.json'), `${JSON.stringify(record.brand, null, 2)}\n`, 'utf-8');
      console.log(`  ${slug}: APPLIED (fields: ${changedFields.join(', ') || 'none'})`);
    } else {
      console.log(`  ${slug}: would apply fields: ${changedFields.join(', ') || '(none)'}`);
    }
    accepted++;
  }

  console.log('');
  if (!args.apply) {
    console.log('PREVIEW only — re-run with --apply to write accepted records.');
  }
  console.log(`Accepted/promotable: ${accepted}`);
  console.log(`Skipped:             ${skipped}`);
  if (rejected.length > 0) {
    console.log('Rejected records:');
    for (const r of rejected) console.log(`  ${r.slug}: ${r.reasons.join('; ')}`);
  }
}

function slugifyCheck(brand, directorySlug) {
  const expected = String(directorySlug).toLowerCase();
  if (brand.slug != null && brand.slug !== expected) {
    return { ok: false, message: `brand.slug "${brand.slug}" != directory "${expected}"` };
  }
  return { ok: true };
}

main().catch((err) => {
  console.error(`Fatal error: ${err.message}`);
  process.exit(1);
});